/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Core health (unauthenticated) */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate the single Administrator with the one-time Bootstrap Code */
        post: operations["bootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify the local username and password, then either issue a Session or require the second-factor step */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/second-factor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a local login challenge with TOTP or a Recovery Code */
        post: operations["completeLocalLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/enrollment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a fresh TOTP enrollment after password re-authentication */
        post: operations["startTOTPEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disable local TOTP after password and current-TOTP proof */
        delete: operations["disableTOTP"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa-enrollment/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a pending member's TOTP enrollment and display Recovery Codes once */
        post: operations["verifyMFAEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa-enrollment/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Recovery Code display and activate the pending member */
        post: operations["confirmMFAEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace the current Session after proof required by the local TOTP policy */
        post: operations["renewSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/step-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a short-lived grant after proof required by the local TOTP policy */
        post: operations["stepUpAuthentication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password after current password and TOTP when the local policy requires it */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Minimal anonymous OIDC availability and binding state */
        get: operations["getOIDCStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start an anonymous OIDC authorization-code transaction */
        get: operations["startOIDCLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate the authorization response and complete login or binding */
        get: operations["completeOIDCTransaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/security": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authenticated local TOTP policy and OIDC binding/configuration state */
        get: operations["getAuthenticationSecurity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/binding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-authenticate locally and start an External Identity Binding transaction */
        post: operations["startOIDCBinding"];
        /** Re-authenticate locally and remove the External Identity Binding */
        delete: operations["deleteOIDCBinding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Destroy the session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current identity and bootstrap state (works without a session) */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications (cursor paginated) */
        get: operations["listApplications"];
        put?: never;
        /** Create an Application */
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{appID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one Application with its Environments */
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{appID}/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an explicitly classified Environment inside an Application */
        post: operations["createEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{appID}/environments/{envID}/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Secrets in an Environment */
        get: operations["listSecrets"];
        put?: never;
        /** Create a Secret with its first encrypted value */
        post: operations["createSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/secrets/{secretID}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a Secret (append an immutable Secret Version) */
        post: operations["createSecretVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/secrets/{secretID}/binding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a Secret's File Binding */
        put: operations["updateBinding"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{appID}/environments/{envID}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the mutable Draft (Desired State in progress) */
        get: operations["getDraft"];
        /** Replace Draft selections (optimistic concurrency via If-Match) */
        put: operations["updateDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{appID}/environments/{envID}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Freeze the Draft into an immutable Bundle Revision with an Operation Reason */
        post: operations["publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{appID}/environments/{envID}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new immutable Bundle Revision from an earlier snapshot */
        post: operations["rollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{appID}/environments/{envID}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bundle Revisions (metadata only) */
        get: operations["listRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/node-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Node Groups with members (cursor paginated) */
        get: operations["listNodeGroups"];
        put?: never;
        /** Create a Node Group */
        post: operations["createNodeGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/node-groups/{groupID}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a Managed Node to a Node Group */
        post: operations["addGroupMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/node-groups/{groupID}/nodes/{nodeID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a Managed Node from a Node Group */
        delete: operations["removeGroupMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assignments (cursor paginated) */
        get: operations["listAssignments"];
        put?: never;
        /** Assign a Secret Bundle to a Node Group (follows the Desired Revision) */
        post: operations["createAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/{assignmentID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assignment and its per-node Unassignment tasks */
        get: operations["unassignmentState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/{assignmentID}/unassign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start persistent two-phase Unassignment for a Bundle Assignment */
        post: operations["unassign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/{assignmentID}/abandon-cleanup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop waiting for unreachable nodes; records cleanup_unconfirmed per node */
        post: operations["abandonCleanup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{appID}/environments/{envID}/activation-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the Environment's Activation Policy */
        get: operations["getActivationPolicy"];
        /** Define the ordered 1-5 unit list and bounded action for an Environment */
        put: operations["putActivationPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Managed Nodes and their convergence state (cursor paginated) */
        get: operations["listNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timestamped read-only Overview projection */
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/install-command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a ten-minute single-use Enrollment Token and Install Command */
        post: operations["createInstallCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Events (never contains Secret values) */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global search across Applications, Environments, Nodes, and Node Groups */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            status: string;
            service: string;
            version: string;
        };
        AdminRef: {
            id: string;
            name: string;
        };
        BootstrapResponse: {
            id: string;
            username: string;
            /** @enum {string} */
            status: "active";
            csrf_token: string;
            /** @enum {string} */
            role: "administrator";
            /** Format: date-time */
            expires_at: string;
        };
        SecondFactorRequired: {
            /** @enum {string} */
            status: "second_factor_required";
            /** @enum {string} */
            code: "second_factor_required";
        };
        TOTPEnrollmentStarted: {
            username: string;
            enrollment_token: string;
            totp_uri: string;
        };
        OIDCPublicStatus: {
            available: boolean;
            bound: boolean;
            login_available: boolean;
        };
        OIDCBindingProof: {
            password: string;
            totp_code?: string;
            return_to?: string;
        };
        AuthenticationSecurity: {
            totp_login_required: boolean;
            oidc: {
                available: boolean;
                bound: boolean;
                /** Format: uri */
                issuer?: string;
                display_name?: string;
                configuration_error?: string;
            };
        };
        LoginResponse: {
            csrf_token: string;
            username: string;
            id: string;
            /** @enum {string} */
            role: "administrator" | "viewer";
            /** Format: date-time */
            expires_at: string;
        };
        FullMFARequest: {
            password: string;
            totp_code?: string;
            recovery_code?: string;
        };
        MFAEnrollmentVerified: {
            confirmation_token: string;
            recovery_codes: string[];
        };
        MFAEnrollmentConfirmed: {
            id: string;
            username: string;
            /** @enum {string} */
            status: "active";
        };
        BootstrapRequired: {
            /** @enum {boolean} */
            bootstrap_required: true;
        };
        Me: {
            /** @enum {boolean} */
            bootstrap_required: false;
            organization: {
                display_name: string;
            };
            member: {
                id: string;
                username: string;
                /** @enum {string} */
                role: "administrator" | "viewer";
            };
            csrf_token: string;
            /** Format: date-time */
            session_expires_at: string;
            /** Format: date-time */
            idle_expires_at: string;
            totp_login_required: boolean;
            /** @enum {string} */
            auth_method: "local" | "oidc";
        };
        Application: {
            id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
        };
        Environment: {
            id: string;
            name: string;
            application_id: string;
            /** @enum {string} */
            protection: "standard" | "protected" | "unclassified";
        };
        Binding: {
            path: string;
            /** Format: int64 */
            uid: number;
            /** Format: int64 */
            gid: number;
            /** @description Octal mode, e.g. "0400" */
            mode: string;
        } | null;
        Secret: {
            id: string;
            name: string;
            binding: components["schemas"]["Binding"];
            /** Format: int64 */
            latest_version: number;
            /** Format: int64 */
            selected_version: number;
        };
        DraftSelection: {
            secret_id: string;
            name: string;
            /** Format: int64 */
            version_seq: number;
            binding: components["schemas"]["Binding"];
        };
        Draft: {
            /** Format: int64 */
            version: number;
            selections: components["schemas"]["DraftSelection"][];
        };
        Revision: {
            id: string;
            /** Format: int64 */
            draft_version: number;
            /** Format: int64 */
            file_count: number;
            created_by: string;
            /** Format: date-time */
            created_at: string;
            operation_reason: components["schemas"]["OperationReason"];
        };
        OperationReason: {
            /** @enum {string} */
            category: "maintenance" | "incident_response" | "access_change" | "configuration_correction" | "other";
            explanation: string;
            external_ref?: string;
        };
        NodeGroup: {
            id: string;
            name: string;
            member_ids: string[];
        };
        Assignment: {
            id: string;
            group_id: string;
            group_name: string;
            application_id: string;
            environment_id: string;
            /** @description Current Desired Revision, advanced by Publish and Rollback */
            revision_id: string;
            /** @enum {string} */
            status: "active" | "removing";
            /** Format: date-time */
            created_at: string;
        };
        UnassignmentTask: {
            assignment_id: string;
            node_id: string;
            /** @enum {string} */
            status: "pending" | "cleaned" | "failed" | "offline" | "cleanup_unconfirmed";
            error?: string;
            /** Format: date-time */
            updated_at: string | null;
        };
        ActivationPolicy: {
            units: string[];
            /** @enum {string} */
            action: "none" | "reload" | "restart";
        };
        Node: {
            id: string;
            name: string;
            serial: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_seen_at: string | null;
            desired_etag: string;
            observed_revision: string;
            last_result: string;
            /**
             * @description Derived primary state (ADR-0015)
             * @enum {string}
             */
            state: "never_online" | "healthy" | "converging" | "failed" | "offline";
            unassigned: boolean;
        };
        Overview: {
            /** Format: date-time */
            generated_at: string;
            counts: {
                applications: number;
                environments: number;
                secrets: number;
                nodes: number;
                node_groups: number;
                assignments: number;
                audit_events: number;
            };
            attention: {
                /** @enum {string} */
                kind: "failed_convergence" | "offline_node" | "unassigned_node" | "unclassified_environment" | "cleanup_failed" | "cleanup_unconfirmed";
                count: number;
                resource?: string;
            }[];
            recent_publishes: components["schemas"]["Revision"][];
            recent_audit: components["schemas"]["AuditEvent"][];
        };
        InstallCommand: {
            /** @description curl | sudo bash Install Command carrying the one-time Token */
            command: string;
            /** Format: date-time */
            expires_at: string;
        };
        AuditEvent: {
            /** Format: int64 */
            id: number;
            actor: string;
            action: string;
            resource: string;
            result: string;
            correlation_id: string;
            /** Format: date-time */
            created_at: string;
            actor_type: string;
            actor_id: string;
            /** @description Event-time display snapshot; renames never rewrite history */
            actor_display: string;
            resource_type: string;
            resource_id: string;
            resource_display: string;
            outcome: string;
            operation_reason_category?: string;
            operation_reason_explanation?: string;
            operation_reason_external_ref?: string;
        };
        Page: {
            items: components["schemas"]["Application"][];
            /** @description Opaque keyset position; empty on the last page */
            next_cursor: string;
        };
        NodeGroupPage: {
            items: components["schemas"]["NodeGroup"][];
            next_cursor: string;
        };
        AssignmentPage: {
            items: components["schemas"]["Assignment"][];
            next_cursor: string;
        };
        NodePage: {
            items: components["schemas"]["Node"][];
            next_cursor: string;
        };
        AuditEventPage: {
            items: components["schemas"]["AuditEvent"][];
            next_cursor: string;
        };
        Error: {
            /** @description Human-readable message; never parse it */
            error: string;
            /**
             * @description Stable machine-readable code; switch on this
             * @enum {string}
             */
            code: "bad_request" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "duplicate" | "internal" | "unavailable" | "payload_too_large" | "mfa_enrollment_required" | "second_factor_required" | "challenge_expired" | "rate_limited";
        };
    };
    responses: {
        /** @description Request payload or validation failure */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or expired session */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid CSRF token or forbidden action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Referenced resource does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description State conflict (e.g. stale Draft version) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A uniquely named resource already exists */
        Duplicate: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Dependency or configuration missing (e.g. install flow disabled) */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication attempt rate limit exceeded */
        RateLimited: {
            headers: {
                /** @description Seconds until the current failure window expires */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Application id (UUID) */
        AppID: string;
        /** @description Environment id (UUID) */
        EnvID: string;
        /** @description Assignment id (UUID) */
        AssignmentID: string;
        /** @description Secret id (UUID) */
        SecretID: string;
        /** @description Node Group id (UUID) */
        GroupID: string;
        /** @description Managed Node id (UUID) */
        NodeID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    bootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description One-time Bootstrap Code printed by Core on first boot */
                    code: string;
                    organization_name: string;
                    username: string;
                    /** @description Argon2id-hashed server-side; never stored in clear */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Active Administrator and Session created */
            201: {
                headers: {
                    /** @description autosecrets_session (HttpOnly, SameSite=Lax) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Authenticated; Set-Cookie carries the session */
            200: {
                headers: {
                    /** @description autosecrets_session (HttpOnly, SameSite=Lax) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Password accepted; a short-lived second-factor challenge was issued */
            202: {
                headers: {
                    /** @description autosecrets_login_challenge (HttpOnly, SameSite=Lax) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecondFactorRequired"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    completeLocalLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    totp_code?: string;
                    recovery_code?: string;
                };
            };
        };
        responses: {
            /** @description Authenticated; Set-Cookie carries the Session */
            200: {
                headers: {
                    /** @description autosecrets_session and expired challenge cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    startTOTPEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description Fresh enrollment with a one-time TOTP URI */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TOTPEnrollmentStarted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    disableTOTP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                    totp_code: string;
                };
            };
        };
        responses: {
            /** @description TOTP disabled and credentials removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        totp_login_required: false;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    verifyMFAEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enrollment_token: string;
                    totp_code: string;
                };
            };
        };
        responses: {
            /** @description One-time Recovery Code display */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MFAEnrollmentVerified"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    confirmMFAEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    confirmation_token: string;
                };
            };
        };
        responses: {
            /** @description Member activated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MFAEnrollmentConfirmed"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    renewSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FullMFARequest"];
            };
        };
        responses: {
            /** @description Renewed Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    stepUpAuthentication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FullMFARequest"];
            };
        };
        responses: {
            /** @description Session-bound Step-up Grant issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        expires_at: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    current_password: string;
                    new_password: string;
                    totp_code?: string;
                };
            };
        };
        responses: {
            /** @description Password changed and current browser Session reissued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getOIDCStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OIDC availability without operational diagnostics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OIDCPublicStatus"];
                };
            };
        };
    };
    startOIDCLogin: {
        parameters: {
            query?: {
                return_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the discovered Provider authorization endpoint */
            302: {
                headers: {
                    Location?: string;
                    /** @description Short-lived autosecrets_oidc_state cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    completeOIDCTransaction: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OIDC transaction completed and redirected to a validated local path */
            302: {
                headers: {
                    Location?: string;
                    /** @description Expired state cookie and, for login, the AutoSecrets Session */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAuthenticationSecurity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sanitized authentication security state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationSecurity"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    startOIDCBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OIDCBindingProof"];
            };
        };
        responses: {
            /** @description Provider authorization URL for the binding transaction */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        authorization_url: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteOIDCBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OIDCBindingProof"];
            };
        };
        responses: {
            /** @description External Identity Binding removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        bound: false;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bootstrap state, and the session when one exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapRequired"] | components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listApplications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Applications newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Application created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Duplicate"];
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application id (UUID) */
                appID: components["parameters"]["AppID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        environments: components["schemas"]["Environment"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application id (UUID) */
                appID: components["parameters"]["AppID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /**
                     * @description Explicit classification; never inferred from the name
                     * @enum {string}
                     */
                    protection: "standard" | "protected";
                };
            };
        };
        responses: {
            /** @description Environment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Duplicate"];
        };
    };
    listSecrets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application id (UUID) */
                appID: components["parameters"]["AppID"];
                /** @description Environment id (UUID) */
                envID: components["parameters"]["EnvID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Secrets ordered by name; never includes Secret values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Secret"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application id (UUID) */
                appID: components["parameters"]["AppID"];
                /** @description Environment id (UUID) */
                envID: components["parameters"]["EnvID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Must not contain '/' or NUL */
                    name: string;
                    /** @description Opaque Secret bytes, encrypted before persistence */
                    value: string;
                };
            };
        };
        responses: {
            /** @description Secret created and selected in the Draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Duplicate"];
        };
    };
    createSecretVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Secret id (UUID) */
                secretID: components["parameters"]["SecretID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    value: string;
                };
            };
        };
        responses: {
            /** @description New version appended and selected in the Draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        seq: number;
                        /** Format: int64 */
                        draft_version: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Secret id (UUID) */
                secretID: components["parameters"]["SecretID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Relative POSIX path; rejects absolute, '.', '..', control chars */
                    path: string;
                    /** Format: int64 */
                    uid?: number;
                    /** Format: int64 */
                    gid?: number;
                    /** @description Octal mode, one of 0400 0440 0444 0600 0640 0644 */
                    mode: string;
                };
            };
        };
        responses: {
            /** @description Binding updated and Draft bumped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        draft_version: number;
                        path: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application id (UUID) */
                appID: components["parameters"]["AppID"];
                /** @description Environment id (UUID) */
                envID: components["parameters"]["EnvID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft with optimistic-concurrency version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateDraft: {
        parameters: {
            query?: never;
            header?: {
                /** @description Expected Draft version; a stale value yields 409 conflict */
                "If-Match"?: string;
            };
            path: {
                /** @description Application id (UUID) */
                appID: components["parameters"]["AppID"];
                /** @description Environment id (UUID) */
                envID: components["parameters"]["EnvID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Secret ID to Secret Version sequence (full replacement map) */
                    selections: {
                        [key: string]: number;
                    };
                };
            };
        };
        responses: {
            /** @description Draft updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        draft_version: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application id (UUID) */
                appID: components["parameters"]["AppID"];
                /** @description Environment id (UUID) */
                envID: components["parameters"]["EnvID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    operation_reason?: components["schemas"]["OperationReason"];
                };
            };
        };
        responses: {
            /** @description Bundle Revision created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    rollback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application id (UUID) */
                appID: components["parameters"]["AppID"];
                /** @description Environment id (UUID) */
                envID: components["parameters"]["EnvID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    source_revision_id: string;
                    operation_reason?: components["schemas"]["OperationReason"];
                };
            };
        };
        responses: {
            /** @description Rollback Bundle Revision created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application id (UUID) */
                appID: components["parameters"]["AppID"];
                /** @description Environment id (UUID) */
                envID: components["parameters"]["EnvID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revisions newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listNodeGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node Groups newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeGroupPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createNodeGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Node Group created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Duplicate"];
        };
    };
    addGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node Group id (UUID) */
                groupID: components["parameters"]["GroupID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    node_id: string;
                };
            };
        };
        responses: {
            /** @description Member added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    removeGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Node Group id (UUID) */
                groupID: components["parameters"]["GroupID"];
                /** @description Managed Node id (UUID) */
                nodeID: components["parameters"]["NodeID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignments newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    group_id: string;
                    application_id: string;
                    environment_id: string;
                    operation_reason?: components["schemas"]["OperationReason"];
                };
            };
        };
        responses: {
            /** @description Assignment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Duplicate"];
        };
    };
    unassignmentState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Assignment id (UUID) */
                assignmentID: components["parameters"]["AssignmentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignment and cleanup tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        assignment: components["schemas"]["Assignment"];
                        tasks: components["schemas"]["UnassignmentTask"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    unassign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Assignment id (UUID) */
                assignmentID: components["parameters"]["AssignmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    operation_reason?: components["schemas"]["OperationReason"];
                };
            };
        };
        responses: {
            /** @description Unassignment started with per-node tasks */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        /** @enum {string} */
                        status: "removing";
                        tasks: components["schemas"]["UnassignmentTask"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    abandonCleanup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Assignment id (UUID) */
                assignmentID: components["parameters"]["AssignmentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    operation_reason?: components["schemas"]["OperationReason"];
                };
            };
        };
        responses: {
            /** @description Control-plane waiting ended with unconfirmed local cleanup */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "cleanup_unconfirmed";
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getActivationPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application id (UUID) */
                appID: components["parameters"]["AppID"];
                /** @description Environment id (UUID) */
                envID: components["parameters"]["EnvID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activation Policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivationPolicy"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    putActivationPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application id (UUID) */
                appID: components["parameters"]["AppID"];
                /** @description Environment id (UUID) */
                envID: components["parameters"]["EnvID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    units: string[];
                    /** @enum {string} */
                    action: "none" | "reload" | "restart";
                    operation_reason: components["schemas"]["OperationReason"];
                };
            };
        };
        responses: {
            /** @description Activation Policy stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivationPolicy"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nodes newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overview projection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createInstallCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Optional node name; a random one is generated when absent */
                    name?: string;
                    /**
                     * @description Optional override of the deployment root for the
                     *     Materialized Bundle on the node. Defaults to
                     *     ~/.autosecrets in the invoking user's home (the legacy
                     *     tool's layout); "~" expands to the sudo caller's home.
                     */
                    bundle_dir?: string;
                };
            };
        };
        responses: {
            /** @description Install Command; the Token appears in this response only */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallCommand"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                /** @description Filter by exact actor */
                actor?: string;
                /** @description Filter by exact action */
                action?: string;
                /** @description Page size (default 25, max 100) */
                limit?: number;
                /** @description Opaque keyset position from the previous page */
                cursor?: string;
                /** @description Filter by exact resource display */
                resource?: string;
                /** @description Filter by exact outcome code */
                outcome?: string;
                /** @description Filter by Operation Reason category */
                reason_category?: string;
                /** @description Inclusive lower bound (RFC 3339) */
                from?: string;
                /** @description Inclusive upper bound (RFC 3339) */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit Events newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grouped search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results: {
                            /** @enum {string} */
                            type: "application" | "environment" | "node" | "node_group";
                            id: string;
                            name: string;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
