package envelope

import (
	"encoding/base64"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"testing"
	"time"

	"filippo.io/age"
)

type vector struct {
	Name             string   `json:"name"`
	Note             string   `json:"note"`
	Envelope         Envelope `json:"envelope"`
	RecipientPublic  string   `json:"recipient_public"`
	RecipientPrivate string   `json:"recipient_private"`
	SigningPublic    string   `json:"signing_public"`
	SigningPrivate   string   `json:"signing_private"`
	Manifest         string   `json:"manifest"`
	Plaintext        string   `json:"plaintext"`
	MustFail         string   `json:"must_fail,omitempty"`
}

type vectorFile struct {
	Protocol string   `json:"protocol"`
	Version  int      `json:"version"`
	Vectors  []vector `json:"vectors"`
}

func vectorsPath(t *testing.T) string {
	t.Helper()
	return filepath.Join(repoRootDir(t), "api", "agent-envelope", "testdata", "envelope-v1-vectors.json")
}

func loadVectors(t *testing.T) vectorFile {
	t.Helper()
	data, err := os.ReadFile(vectorsPath(t))
	if err != nil {
		t.Fatal(err)
	}
	var vf vectorFile
	if err := json.Unmarshal(data, &vf); err != nil {
		t.Fatal(err)
	}
	if vf.Protocol != ProtocolName || vf.Version != Version {
		t.Fatalf("vector file protocol mismatch: %s v%d", vf.Protocol, vf.Version)
	}
	return vf
}

func openVector(t *testing.T, v vector, now time.Time) ([]byte, error) {
	t.Helper()
	identity, err := age.ParseX25519Identity(v.RecipientPrivate)
	if err != nil {
		t.Fatal(err)
	}
	pub, err := base64.StdEncoding.DecodeString(v.SigningPublic)
	if err != nil {
		t.Fatal(err)
	}
	plaintext, err := v.Envelope.Open(identity, pub, now)
	return plaintext, err
}

func TestVectorsFromBothImplementations(t *testing.T) {
	now := time.Date(2026, 8, 11, 12, 0, 0, 0, time.UTC)
	for _, v := range loadVectors(t).Vectors {
		t.Run(v.Name, func(t *testing.T) {
			switch v.MustFail {
			case "":
				plaintext, err := openVector(t, v, now)
				if err != nil {
					t.Fatalf("valid vector failed: %v", err)
				}
				want, err := base64.StdEncoding.DecodeString(v.Plaintext)
				if err != nil {
					t.Fatal(err)
				}
				if string(plaintext) != string(want) {
					t.Fatalf("plaintext mismatch: got %q want %q", plaintext, want)
				}
				if err := v.Envelope.VerifyManifest([]byte(v.Manifest)); err != nil {
					t.Fatalf("manifest mismatch: %v", err)
				}
			case "signature":
				if _, err := openVector(t, v, now); !errors.Is(err, ErrBadSignature) {
					t.Fatalf("got %v, want ErrBadSignature", err)
				}
			case "expired":
				if _, err := openVector(t, v, now); !errors.Is(err, ErrExpired) {
					t.Fatalf("got %v, want ErrExpired", err)
				}
			default:
				t.Fatalf("unknown must_fail kind %q", v.MustFail)
			}
		})
	}
}

// TestGenerateVectors rewrites the checked-in vector file when UPDATE_VECTORS=1.
// The Python-produced vector is appended by scripts/gen-python-vector.py so both
// languages contribute known-answer material.
func TestGenerateVectors(t *testing.T) {
	if os.Getenv("UPDATE_VECTORS") != "1" {
		t.Skip("set UPDATE_VECTORS=1 to regenerate")
	}
	identity := mustIdentity(t)
	pub, priv := mustSigner(t)
	manifest := testManifest()
	plaintext := []byte("go-reference-plaintext")
	opts := testOptions(t, identity, priv)
	opts.ExpiresAt = time.Date(2026, 8, 12, 0, 0, 0, 0, time.UTC)
	env, err := New(optsWithPlaintext(opts, plaintext))
	if err != nil {
		t.Fatal(err)
	}

	tampered := *env
	sig, _ := base64.StdEncoding.DecodeString(env.Signature)
	sig[0] ^= 0xff
	tampered.Signature = base64.StdEncoding.EncodeToString(sig)

	expired := *env
	expired.ExpiresAt = "2026-01-01T00:00:00Z"

	vf := vectorFile{
		Protocol: ProtocolName,
		Version:  Version,
		Vectors: []vector{
			{
				Name: "go-produced-v1", Note: "generated by Go reference implementation",
				Envelope: *env, RecipientPublic: identity.Recipient().String(),
				RecipientPrivate: identity.String(), SigningPublic: base64.StdEncoding.EncodeToString(pub),
				SigningPrivate: base64.StdEncoding.EncodeToString(priv),
				Manifest:       string(manifest), Plaintext: base64.StdEncoding.EncodeToString(plaintext),
			},
			{
				Name: "go-produced-tampered-signature-v1", Note: "signature byte flipped",
				Envelope: tampered, RecipientPublic: identity.Recipient().String(),
				RecipientPrivate: identity.String(), SigningPublic: base64.StdEncoding.EncodeToString(pub),
				SigningPrivate: base64.StdEncoding.EncodeToString(priv),
				Manifest:       string(manifest), Plaintext: base64.StdEncoding.EncodeToString(plaintext),
				MustFail: "signature",
			},
			{
				Name: "go-produced-expired-v1", Note: "expires in the past",
				Envelope: expired, RecipientPublic: identity.Recipient().String(),
				RecipientPrivate: identity.String(), SigningPublic: base64.StdEncoding.EncodeToString(pub),
				SigningPrivate: base64.StdEncoding.EncodeToString(priv),
				Manifest:       string(manifest), Plaintext: base64.StdEncoding.EncodeToString(plaintext),
				MustFail: "expired",
			},
		},
	}
	data, err := json.MarshalIndent(vf, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	data = append(data, '\n')
	if err := os.WriteFile(vectorsPath(t), data, 0o644); err != nil {
		t.Fatal(err)
	}
}
