// Package database owns PostgreSQL access: migration application and every
// query the Core service needs, generated by sqlc into the gen sub-package.
// Tests exercise the store through the HTTP seam against a real PostgreSQL.
package database

import (
	"context"
	"fmt"
	"sort"
	"strconv"
	"time"

	"autosecrets.dev/core/internal/database/gen"
	"autosecrets.dev/core/migrations"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Store struct {
	pool *pgxpool.Pool
	q    *gen.Queries
}

func Connect(ctx context.Context, dsn string) (*Store, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("database: connect: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("database: ping: %w", err)
	}
	s := &Store{pool: pool, q: gen.New(pool)}
	if err := s.migrate(ctx); err != nil {
		pool.Close()
		return nil, err
	}
	return s, nil
}

func (s *Store) Close() { s.pool.Close() }

// Exec runs a statement on the pool (used by tests and migrations).
func (s *Store) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	return s.pool.Exec(ctx, sql, args...)
}

func (s *Store) migrate(ctx context.Context) error {
	if _, err := s.pool.Exec(ctx, `CREATE TABLE IF NOT EXISTS schema_migrations (
		name text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now())`); err != nil {
		return fmt.Errorf("database: migrations table: %w", err)
	}
	entries, err := migrations.FS.ReadDir(".")
	if err != nil {
		return err
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		names = append(names, e.Name())
	}
	sort.Strings(names)
	for _, name := range names {
		var applied bool
		if err := s.pool.QueryRow(ctx,
			`SELECT EXISTS (SELECT 1 FROM schema_migrations WHERE name = $1)`, name).Scan(&applied); err != nil {
			return err
		}
		if applied {
			continue
		}
		sqlBytes, err := migrations.FS.ReadFile(name)
		if err != nil {
			return err
		}
		tx, err := s.pool.Begin(ctx)
		if err != nil {
			return err
		}
		if _, err := tx.Exec(ctx, string(sqlBytes)); err != nil {
			_ = tx.Rollback(ctx)
			return fmt.Errorf("database: migrate %s: %w", name, err)
		}
		if _, err := tx.Exec(ctx, `INSERT INTO schema_migrations (name) VALUES ($1)`, name); err != nil {
			_ = tx.Rollback(ctx)
			return err
		}
		if err := tx.Commit(ctx); err != nil {
			return err
		}
	}
	return nil
}

func (s *Store) AdminCount(ctx context.Context) (int, error) {
	n, err := s.q.AdminCount(ctx)
	return int(n), err
}

func (s *Store) AdminByUsername(ctx context.Context, username string) (*Admin, error) {
	return s.MemberByUsername(ctx, username)
}

func (s *Store) CreateAdmin(ctx context.Context, id, username, passwordHash string) error {
	err := s.q.CreateAdmin(ctx, gen.CreateAdminParams{
		ID: id, Username: username, PasswordHash: passwordHash,
		Role: RoleAdministrator, Status: MemberActive,
	})
	if isUniqueViolation(err) {
		return ErrDuplicate
	}
	return err
}

func (s *Store) SaveBootstrapCode(ctx context.Context, codeHash string, expiresAt time.Time) error {
	return s.q.SaveBootstrapCode(ctx, gen.SaveBootstrapCodeParams{CodeHash: codeHash, ExpiresAt: expiresAt})
}

func (s *Store) ConsumeBootstrapCode(ctx context.Context, codeHash string, now time.Time) (bool, error) {
	n, err := s.q.ConsumeBootstrapCode(ctx, gen.ConsumeBootstrapCodeParams{
		CodeHash: codeHash, UsedAt: pgtype.Timestamptz{Time: now, Valid: true},
	})
	if err != nil {
		return false, err
	}
	return n == 1, nil
}

// CreateSession is retained for the original lifecycle tests. New callers
// use CreateBoundedSession so both Session limits are explicit at the call
// site.
func (s *Store) CreateSession(ctx context.Context, idHash, adminID, csrfToken string, expiresAt time.Time) error {
	idleExpiresAt := time.Now().Add(30 * time.Minute)
	if idleExpiresAt.After(expiresAt) {
		idleExpiresAt = expiresAt
	}
	return s.CreateBoundedSession(ctx, idHash, adminID, csrfToken, expiresAt, idleExpiresAt, "local")
}

// SessionRow is the materialized session state for one request.
type SessionRow struct {
	AdminID       string
	Username      string
	Role          string
	CSRFToken     string
	SessionIDHash string
	ExpiresAt     time.Time
	IdleExpiresAt time.Time
	AuthMethod    string
}

func (s *Store) SessionByID(ctx context.Context, idHash string, now time.Time) (*SessionRow, error) {
	row, err := s.q.SessionByID(ctx, gen.SessionByIDParams{
		IDHash: idHash, ExpiresAt: now, Status: MemberActive,
	})
	if err != nil {
		return nil, mapNoRows(err)
	}
	return &SessionRow{
		AdminID: row.AdminID, Username: row.Username, Role: row.Role,
		CSRFToken: row.CsrfToken, SessionIDHash: row.IDHash,
		ExpiresAt: row.ExpiresAt, IdleExpiresAt: row.IdleExpiresAt, AuthMethod: row.AuthMethod,
	}, nil
}

func (s *Store) DeleteSession(ctx context.Context, idHash string) error {
	return s.q.DeleteSession(ctx, idHash)
}

// --- Audit ----------------------------------------------------------------

type AuditEvent struct {
	ID                int64  `json:"id"`
	Actor             string `json:"actor"`
	Action            string `json:"action"`
	Resource          string `json:"resource"`
	Result            string `json:"result"`
	CorrelationID     string `json:"correlation_id"`
	CreatedAt         string `json:"created_at"`
	ActorType         string `json:"actor_type"`
	ActorID           string `json:"actor_id"`
	ActorDisplay      string `json:"actor_display"`
	ResourceType      string `json:"resource_type"`
	ResourceID        string `json:"resource_id"`
	ResourceDisplay   string `json:"resource_display"`
	Outcome           string `json:"outcome"`
	ReasonCategory    string `json:"operation_reason_category"`
	ReasonExplanation string `json:"operation_reason_explanation"`
	ReasonExternalRef string `json:"operation_reason_external_ref"`
}

// AppendAudit inserts an Audit Event inside the caller's transaction when tx
// is non-nil, otherwise in its own transaction. The Audit Event is
// append-only; nothing in this package ever updates or deletes one.
func (s *Store) AppendAudit(ctx context.Context, tx pgx.Tx, e AuditEvent) error {
	q := s.q
	if tx != nil {
		q = s.q.WithTx(tx)
	}
	return q.InsertAuditEvent(ctx, gen.InsertAuditEventParams{
		Actor: e.Actor, Action: e.Action, Resource: e.Resource, Result: e.Result, CorrelationID: e.CorrelationID,
		Column6: e.ActorType, Column7: e.ActorID, Column8: e.ActorDisplay,
		Column9: e.ResourceType, Column10: e.ResourceID, Column11: e.ResourceDisplay,
		Column12: e.Outcome, Column13: e.ReasonCategory, Column14: e.ReasonExplanation, Column15: e.ReasonExternalRef,
	})
}

type AuditFilter struct {
	Actor          string
	Action         string
	Resource       string
	Outcome        string
	ReasonCategory string
	From           time.Time
	To             time.Time
	Limit          int
}

func (s *Store) ListAudit(ctx context.Context, f AuditFilter) ([]AuditEvent, error) {
	if f.Limit <= 0 || f.Limit > 500 {
		f.Limit = 100
	}
	params := gen.ListAuditParams{Limit: int32(f.Limit)}
	if f.Actor != "" {
		params.Actor = &f.Actor
	}
	if f.Action != "" {
		params.Action = &f.Action
	}
	rows, err := s.q.ListAudit(ctx, params)
	if err != nil {
		return nil, err
	}
	out := make([]AuditEvent, len(rows))
	for i, r := range rows {
		out[i] = AuditEvent{
			ID: r.ID, Actor: r.Actor, Action: r.Action, Resource: r.Resource,
			Result: r.Result, CorrelationID: r.CorrelationID, CreatedAt: r.CreatedAt,
		}
	}
	return out, nil
}

// ListAuditPage returns cursor-paginated structured Audit Events ordered by
// id DESC with the documented filters (ADR-0020). The cursor is the last
// visible event id.
func (s *Store) ListAuditPage(ctx context.Context, f AuditFilter, afterID int64) ([]AuditEvent, string, error) {
	if f.Limit <= 0 || f.Limit > 100 {
		f.Limit = 25
	}
	params := gen.ListAuditPageParams{Limit: int32(f.Limit + 1)}
	if afterID > 0 {
		params.AfterID = &afterID
	}
	if f.Actor != "" {
		params.Actor = &f.Actor
	}
	if f.Action != "" {
		params.Action = &f.Action
	}
	if f.Resource != "" {
		params.Resource = &f.Resource
	}
	if f.Outcome != "" {
		params.Outcome = &f.Outcome
	}
	if f.ReasonCategory != "" {
		params.ReasonCategory = &f.ReasonCategory
	}
	if !f.From.IsZero() {
		params.From = pgtype.Timestamptz{Time: f.From, Valid: true}
	}
	if !f.To.IsZero() {
		params.To = pgtype.Timestamptz{Time: f.To, Valid: true}
	}
	rows, err := s.q.ListAuditPage(ctx, params)
	if err != nil {
		return nil, "", err
	}
	out := make([]AuditEvent, len(rows))
	for i, r := range rows {
		out[i] = AuditEvent{
			ID: r.ID, Actor: r.Actor, Action: r.Action, Resource: r.Resource,
			Result: r.Result, CorrelationID: r.CorrelationID, CreatedAt: r.CreatedAt,
			ActorType: r.ActorType, ActorID: r.ActorID, ActorDisplay: r.ActorDisplay,
			ResourceType: r.ResourceType, ResourceID: r.ResourceID, ResourceDisplay: r.ResourceDisplay,
			Outcome: r.Outcome, ReasonCategory: r.OperationReasonCategory,
			ReasonExplanation: r.OperationReasonExplanation, ReasonExternalRef: r.OperationReasonExternalRef,
		}
	}
	if len(out) <= f.Limit {
		return out, "", nil
	}
	return out[:f.Limit], strconv.FormatInt(out[f.Limit].ID, 10), nil
}

// --- transactions ---------------------------------------------------------

func (s *Store) Begin(ctx context.Context) (pgx.Tx, error) {
	return s.pool.Begin(ctx)
}
