#!/usr/bin/env python3
"""Append a Python-produced known-answer vector to the shared vector file.

Run once after the Go generator (UPDATE_VECTORS=1) has created the file:

    agent/.venv/bin/python scripts/gen-python-vector.py

Both language test suites then consume the Python-produced vector, proving the
reverse direction of the interop contract without a live subprocess.
"""

from __future__ import annotations

import base64
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from age.keys.agekey import AgePrivateKey
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "agent" / "src"))
from autosecrets_agent.envelope import create  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
VECTORS = ROOT / "api" / "agent-envelope" / "testdata" / "envelope-v1-vectors.json"


def main() -> int:
    identity = AgePrivateKey.generate()
    signer = Ed25519PrivateKey.generate()
    manifest = (
        b'{"files":[{"gid":"0","mode":"0400","path":"app/token",'
        b'"sha256":"abc123","uid":"1000"}],"protocol":"autosecrets-manifest",'
        b'"version":"1"}'
    )
    plaintext = b"python-reference-plaintext"
    envelope = create(
        plaintext=plaintext,
        manifest=manifest,
        recipient_pub=identity.public_key(),
        signer=signer,
        node_id="node-py",
        revision_id="rev-py",
        created_at=datetime(2026, 8, 11, tzinfo=timezone.utc),
        expires_at=datetime(2026, 8, 12, tzinfo=timezone.utc),
        signing_key_id="py-signing-1",
    )
    data = json.loads(VECTORS.read_text(encoding="utf-8"))
    data["vectors"] = [
        v for v in data["vectors"] if v["name"] != "python-produced-v1"
    ]
    data["vectors"].append(
        {
            "name": "python-produced-v1",
            "note": "generated by Python agent implementation",
            "envelope": json.loads(envelope.to_json()),
            "recipient_public": identity.public_key().public_string(),
            "recipient_private": identity.private_string(),
            "signing_public": base64.b64encode(signer.public_key().public_bytes_raw()).decode(),
            "signing_private": "",
            "manifest": manifest.decode(),
            "plaintext": base64.b64encode(plaintext).decode(),
        }
    )
    VECTORS.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print("appended python-produced-v1")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
